package be.uliege.boigelot.oop.sokoban.main.cell;

public enum CellType {
	CRATE, CRATE2, EMPTY, TARGET, WALL, PLAYER,
	CLEAR, GOLD, ARROW, 
	MARIO, MARIO_SHOP, CINNAMOROLL, CINNAMOROLL_SHOP, FRISK, FRISK_SHOP, CYNTHIA, CYNTHIA_SHOP,
	ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT
}